version: "2"
services:

    social-server:
        build: ./server
        restart: always
        container_name: social-server
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        volumes:
            - ./server:/server
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
            - MONGO_CONNECTION_STRING_ADMIN=${MONGO_CONNECTION_STRING_ADMIN}
            - WAIT_HOSTS=db:${MONGO_PORT}
        depends_on:
            - db
        restart: on-failure

    social-client:
        build: ./client
        restart: on-failure
        container_name: social-client
        ports:
            - "${REACT_APP_PORT}:${REACT_APP_PORT}"
        volumes:
            - ./client:/client
        depends_on:
        - social-server
        restart: on-failure

    db:
        image: mongo:latest
        volumes:
            - $DATABASE_DATA:/$DATABASE_DATA
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        restart: on-failure
        expose:
            - ${MONGO_PORT}