FROM node:12.6.0
ADD . /server
WORKDIR /server
COPY . /server
RUN npm install
RUN npm install -g nodemon
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
CMD /wait && npm start
ENV PORT 5000

